import {useCallback,useEffect,useMemo,useState} from 'react';
import {api} from '../services/api.js';

const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n));
const icons={Balones:'⚽',Playeras:'👕',Tenis:'👟',Accesorios:'🧤'};
export default function App(){
 const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem('cancha-session'))}catch{return null}}),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[users,setUsers]=useState([]),[cart,setCart]=useState({}),[filter,setFilter]=useState('Todos'),[modal,setModal]=useState(''),[editing,setEditing]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const loadProducts=useCallback(async()=>setProducts(await api.products()),[]);
 const loadOrders=useCallback(async()=>{if(session)setOrders(await api.orders(session.token));else setOrders([])},[session]);
 const loadUsers=useCallback(async()=>{if(session?.user.role==='admin')setUsers(await api.users(session.token));else setUsers([])},[session]);
 const refresh=useCallback(async()=>{try{await Promise.all([loadProducts(),loadOrders(),loadUsers()])}catch(e){setMessage(e.message)}},[loadProducts,loadOrders,loadUsers]);
 useEffect(()=>{refresh()},[refresh]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),3800);return()=>clearTimeout(t)}},[message]);
 const categories=useMemo(()=>['Todos',...new Set(products.map(p=>p.category))],[products]);
 const visible=products.filter(p=>filter==='Todos'||p.category===filter),count=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((a,p)=>a+(Number(cart[p.id]||0)*Number(p.price)),0),admin=session?.user.role==='admin';
 function saveSession(data){setSession(data);localStorage.setItem('cancha-session',JSON.stringify(data));setModal('');setMessage(`¡Qué bueno verte, ${data.user.name}!`)}
 async function submitAuth(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{saveSession(await (modal==='register'?api.register({name:f.get('name'),email:f.get('email'),password:f.get('password')}):api.login({email:f.get('email'),password:f.get('password')})))}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function checkout(){if(!session){setModal('login');return}if(!count)return;setBusy(true);try{const result=await api.createOrder(session.token,Object.entries(cart).map(([productId,quantity])=>({productId:Number(productId),quantity})));setCart({});await refresh();setMessage(`Pedido #${result.order.id} registrado como pendiente de pago. ${result.emailStatus?.sent?'Enviamos las instrucciones a tu correo.':'El pedido quedó registrado; revisa la configuración de correo con la tienda.'}`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function saveProduct(e){e.preventDefault();const f=new FormData(e.currentTarget),data={name:f.get('name'),description:f.get('description'),category:f.get('category'),price:Number(f.get('price')),stock:Number(f.get('stock'))};try{if(editing)await api.updateProduct(session.token,editing.id,data);else await api.createProduct(session.token,data);setModal('');setEditing(null);await loadProducts();setMessage('Catálogo actualizado.')}catch(e){setMessage(e.message)}}
 async function deleteProduct(id){if(!confirm('¿Eliminar este producto del catálogo?'))return;try{await api.deleteProduct(session.token,id);await loadProducts();setMessage('Producto eliminado.')}catch(e){setMessage(e.message)}}
 async function updateOrder(id,status){try{await api.updateOrder(session.token,id,status);await Promise.all([loadOrders(),loadProducts()]);setMessage(status==='cancelled'?'Pedido cancelado; inventario restituido.':'Pedido actualizado.')}catch(e){setMessage(e.message)}}
 async function deleteOrder(id){if(!confirm('¿Eliminar este pedido pendiente?'))return;try{await api.deleteOrder(session.token,id);await Promise.all([loadOrders(),loadProducts()]);setMessage('Pedido eliminado.')}catch(e){setMessage(e.message)}}
 async function updateRole(u){try{await api.updateUser(session.token,u.id,{role:u.role==='admin'?'customer':'admin'});await loadUsers();setMessage('Rol actualizado.')}catch(e){setMessage(e.message)}}
 async function deleteUser(u){if(!confirm(`¿Eliminar la cuenta de ${u.name}?`))return;try{await api.deleteUser(session.token,u.id);await loadUsers();setMessage('Usuario eliminado.')}catch(e){setMessage(e.message)}}
 function logout(){setSession(null);localStorage.removeItem('cancha-session');setOrders([]);setUsers([]);setMessage('Sesión cerrada.')}
 return <><header className="nav"><a className="brand" href="#inicio"><span className="brand-ball">⚽</span> CANCHA<span className="accent">ONCE</span></a><nav><a href="#catalogo">Catálogo</a><a href="#pedidos">Pedidos</a>{admin&&<a href="#usuarios">Usuarios</a>}</nav><div className="nav-actions">{session?<><span className="welcome">{session.user.name.split(' ')[0]}{admin?' · Admin':''}</span><button className="button small ghost" onClick={logout}>Salir</button></>:<button className="button small ghost" onClick={()=>setModal('login')}>Ingresar</button>}<a className="bag" href="#bolsa">Bolsa <span>{count}</span></a></div></header>
 <main id="inicio"><section className="hero"><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> EQUIPAMIENTO PARA CADA PARTIDO</div><h1>VIVE EL<br/> <span>JUEGO.</span></h1><p>Equipo seleccionado para jugar mejor. Diseño, comodidad y rendimiento en cada minuto.</p><a className="button primary" href="#catalogo">Descubrir colección <span>↘</span></a><div className="hero-note"><span>✳</span> FÚTBOL PARA TODOS<br/> HECHO PARA LA CANCHA</div></div><div className="ball-art"><img className="hero-photo" src="https://images.unsplash.com/photo-1721257001239-60fe6a768dbb?auto=format&fit=crop&w=1400&q=85" alt="Balón de fútbol sobre el césped, listo para el partido"/><div className="hero-photo-caption"><span>COLECCIÓN 2025</span><span>01 — BALONES</span></div></div><span className="hero-index">01 / 04</span></div><div className="ticker"><div>CALIDAD PARA CADA PARTIDO <span>✳</span> PRODUCTOS PARA VIVIR EL FÚTBOL <span>✳</span> CALIDAD PARA CADA PARTIDO <span>✳</span> PRODUCTOS PARA VIVIR EL FÚTBOL</div></div></section>
 <section className="shop section" id="catalogo"><div className="section-head"><div><div className="eyebrow dark">01 — LA COLECCIÓN</div><h2>EQUÍPATE PARA<br/><span>EL PARTIDO.</span></h2></div><p>Selección de balones, tenis y accesorios<br/>para salir a la cancha con confianza.</p></div><div className="catalog-tools"><div className="filters">{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div>{admin&&<button className="button primary" onClick={()=>{setEditing(null);setModal('product')}}>＋ Nuevo producto</button>}</div><div className="product-grid">{visible.map((p,i)=><article className="product" key={p.id}><div className={`product-picture picture-${i%4}`}>{p.image_url?<img className="product-photo" src={p.image_url} alt={p.name} loading="lazy"/>:<span className="product-icon">{icons[p.category]||'⚽'}</span>}<span className="product-index">CANCHA ONCE / {String(i+1).padStart(2,'0')}</span><span className="product-kind">{p.category}</span>{admin&&<button className="product-edit" onClick={()=>{setEditing(p);setModal('product')}} aria-label="Editar producto">✎</button>}</div><div className="product-info"><div><h3>{p.name}</h3><p>{p.description}</p></div><strong>{money(p.price)}</strong></div><div className="product-bottom"><span>{p.stock>0?`${p.stock} disponibles`:'AGOTADO'}</span><button disabled={p.stock<1} onClick={()=>setCart(c=>({...c,[p.id]:Math.min((c[p.id]||0)+1,Number(p.stock))}))}>AGREGAR +</button></div>{admin&&<button className="delete-link" onClick={()=>deleteProduct(p.id)}>Eliminar del catálogo</button>}</article>)}</div></section>
 <section className="order-area"><div className="order-columns"><div className="cart-card" id="bolsa"><div className="eyebrow dark">02 — TU SELECCIÓN</div><h2>LA BOLSA<span>.</span></h2>{count===0?<p className="empty">Tu próxima jugada empieza aquí.<br/>Sumá productos desde el catálogo.</p>:<><div className="cart-lines">{products.filter(p=>cart[p.id]).map(p=><div className="cart-line" key={p.id}><span>{icons[p.category]} {p.name} × {cart[p.id]}</span><div><strong>{money(p.price*cart[p.id])}</strong><button onClick={()=>setCart(c=>{const n={...c};n[p.id]--;if(!n[p.id])delete n[p.id];return n})}>−</button><button onClick={()=>setCart(c=>({...c,[p.id]:Math.min(c[p.id]+1,Number(p.stock))}))}>＋</button></div></div>)}</div><div className="cart-total"><span>TOTAL</span><strong>{money(total)}</strong></div><button className="button primary checkout" disabled={busy} onClick={checkout}>Confirmar pedido ↗</button></>}</div><div className="orders-card" id="pedidos"><div className="eyebrow">03 — HISTORIAL</div><h2>EN LA <span>CANCHA.</span></h2>{!session?<p className="empty">Ingresa a tu cuenta para<br/>ver tus pedidos.</p>:orders.length===0?<p className="empty">Todavía no hay pedidos.<br/>El partido te espera. ⚽</p>:<div className="orders-list">{orders.map(o=><article className="order-item" key={o.id}><div className="order-title"><div><span className="order-number">PEDIDO #{o.id}</span><span className={`status status-${o.status}`}>{o.status}</span></div><b>{money(o.total)}</b></div><p>{o.items.map(i=>`${i.name} ×${i.quantity}`).join(' · ')}</p><time>{new Date(o.created_at).toLocaleDateString('es-MX')}</time><div className="order-actions">{admin&&o.status!=='cancelled'&&o.status!=='shipped'&&<button onClick={()=>updateOrder(o.id,o.status==='pending'?'paid':'shipped')}>Marcar {o.status==='pending'?'pagado':'enviado'} →</button>}{o.status==='pending'&&<button onClick={()=>updateOrder(o.id,'cancelled')}>Cancelar</button>}{(admin||o.status==='pending')&&<button onClick={()=>deleteOrder(o.id)}>Eliminar</button>}</div></article>)}</div>}</div></div></section>
 {admin&&<section className="users-section section" id="usuarios"><div className="section-head"><div><div className="eyebrow dark">04 — EQUIPO</div><h2>LAS PERSONAS<br/>DE <span>LA TRIBUNA.</span></h2></div><p>Administrá las cuentas y permisos<br/>de la tienda.</p></div><div className="users-list">{users.map(u=><article className="user-row" key={u.id}><span className="user-avatar">{u.name.slice(0,1).toUpperCase()}</span><div><strong>{u.name}</strong><small>{u.email}</small></div><span className={`role ${u.role}`}>{u.role==='admin'?'ADMINISTRADOR':'CLIENTE'}</span><div className="user-actions"><button onClick={()=>updateRole(u)}>{u.role==='admin'?'Quitar admin':'Hacer admin'}</button><button onClick={()=>deleteUser(u)}>Eliminar</button></div></article>)}</div></section>}</main>
 <footer><div className="brand"><span className="brand-ball">⚽</span> CANCHA<span className="accent">ONCE</span></div><p>EL FÚTBOL NOS UNE. <span>✳</span> HECHO PARA VIVIRLO.</p><a className="photo-credit" href="https://unsplash.com/license" target="_blank" rel="noreferrer">FOTOGRAFÍA · UNSPLASH</a><span>© 2025 CANCHA ONCE</span></footer>
 {message&&<div className="toast" role="status">{message}<button onClick={()=>setMessage('')}>✕</button></div>}
 {modal&&<div className="modal-backdrop" onClick={()=>{setModal('');setEditing(null)}}><section className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>{setModal('');setEditing(null)}}>✕</button>{modal==='login'||modal==='register'?<><div className="eyebrow dark">CANCHA ONCE · MI CUENTA</div><h2>{modal==='login'?'QUÉ BUENO':'ÚNETE A LA'}<br/><span>{modal==='login'?'TENERTE.':'TRIBUNA.'}</span></h2><form className="form" onSubmit={submitAuth}>{modal==='register'&&<label>Nombre<input name="name" minLength="2" required maxLength="100" placeholder="Tu nombre"/></label>}<label>Correo electrónico<input type="email" name="email" autoComplete="email" required placeholder="tu@correo.com"/></label><label>Contraseña<input type="password" name="password" autoComplete={modal==='register'?'new-password':'current-password'} minLength="10" required placeholder={modal==='register'?'10 caracteres, mayúscula, minúscula y número':'Tu contraseña'}/></label><button className="button primary" disabled={busy}>{busy?'Un momento…':modal==='register'?'Crear mi cuenta ↗':'Iniciar sesión ↗'}</button></form><button className="switch" onClick={()=>setModal(modal==='login'?'register':'login')}>{modal==='login'?'¿Aún no tienes cuenta? Regístrate':'¿Ya tienes cuenta? Inicia sesión'}</button></>:<><div className="eyebrow dark">GESTIÓN DEL CATÁLOGO</div><h2>{editing?'EDITAR':'NUEVO'}<br/><span>PRODUCTO.</span></h2><form className="form" onSubmit={saveProduct}><label>Nombre<input name="name" required maxLength="140" defaultValue={editing?.name}/></label><label>Descripción<input name="description" defaultValue={editing?.description}/></label><label>Categoría<select name="category" defaultValue={editing?.category||'Balones'}>{['Balones','Playeras','Tenis','Accesorios'].map(c=><option key={c}>{c}</option>)}</select></label><div className="field-pair"><label>Precio (MXN)<input name="price" type="number" min="0.01" step="1" required defaultValue={editing?.price}/></label><label>Inventario<input name="stock" type="number" min="0" step="1" required defaultValue={editing?.stock}/></label></div><button className="button primary">Guardar cambios ↗</button></form></>}</section></div>}</>;
}
