import 'dotenv/config';
import { createUseCases } from './application/use-cases.js';
import { createHttpApp } from './infrastructure/http.js';
import { pool } from './infrastructure/postgres.js';
import { orders, products, users } from './infrastructure/repositories.js';
import { passwordHasher, tokenService } from './infrastructure/security.js';
const required=['DATABASE_URL','JWT_SECRET'];
for(const key of required)if(!process.env[key])throw new Error(`Falta configurar ${key}. Copia server/.env.example a server/.env.`);
if(process.env.JWT_SECRET.length<32)throw new Error('JWT_SECRET debe tener al menos 32 caracteres.');
const port=Number(process.env.PORT??3000);
const services=createUseCases({users,products,orders,passwords:passwordHasher,tokens:tokenService});
const app=createHttpApp({services,tokens:tokenService});
const server=app.listen(port,()=>console.log(`⚽ API lista en http://localhost:${port}`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(async()=>{await pool.end();process.exit(0);}));
